happy:
  code:
    swagger:
      base-package: cool.happycoding.code.cache.sample
      enable: true
      group: happy-code-starter-cache-sample
      title: cache组件使用示例
      contact:
        email: happycoding@aliyun.com
        url: https://github.com/happy-coding-cool/happy-code/issues
        name: lanlanhappy
spring:
  redis:
    url: redis://127.0.0.1:6379/
    lettuce:
      pool:
        max-active: 8
        min-idle: 2