happy:
  code:
    swagger:
      base-package: cool.happycoding.code.log.sample
      enable: true
      group: happy-code-starter-log-sample
      title: log组件使用示例
      contact:
        email: happycoding@aliyun.com
        url: https://github.com/happy-coding-cool/happy-code/issues
        name: lanlanhappy
    log:
      enable-print-request: true
      enable-print-response: true
      enable-print-header: true